// Central link registry — single source of truth for all in-app navigation.
// Any clickable element that navigates internally MUST use a value from here.
export const appRoutes = {
  home: "/",
  start: "/start",
  quitPathway: "/quit-pathway",
  helpPathway: "/help-pathway",
  challengePathway: "/challenge-pathway",
  learnTrain: "/learn-train",
  certificates: "/certificates",
  requestSupport: "/request-support",
  professionalLibrary: "/professional-library",
  impact: "/impact",
  about: "/about",
  faq: "/faq",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  medicalDisclaimer: "/medical-disclaimer",
  sharingPolicy: "/sharing-policy",
  cookies: "/cookies",
  staffLogin: "/auth",
  inviteFriends: "/invite-friends",
  supportInvite: "/support-invite",
  quitPlan: "/quit-plan",
  cravingCoach: "/craving-coach",
  relapseSupport: "/relapse-support",
  safetyGuidance: "/safety-guidance",
  whenToSeekHelp: "/when-to-seek-help",
  assessment: "/assessment",
  english: "/en",
  // External
  whatsapp: "https://wa.me/966555096412",
  instagram: "https://www.instagram.com/smokeOffKSA",
  x: "https://x.com/SmokeOffKSA",
  tiktok: "https://www.tiktok.com/@SmokeOffKSA",
  youtube: "https://www.youtube.com/@La-tatten",
} as const;

export const internalRoutes: ReadonlySet<string> = new Set([
  appRoutes.home,
  appRoutes.start,
  appRoutes.quitPathway,
  appRoutes.helpPathway,
  appRoutes.challengePathway,
  appRoutes.learnTrain,
  appRoutes.certificates,
  appRoutes.requestSupport,
  appRoutes.professionalLibrary,
  appRoutes.impact,
  appRoutes.about,
  appRoutes.faq,
  appRoutes.contact,
  appRoutes.privacy,
  appRoutes.terms,
  appRoutes.medicalDisclaimer,
  appRoutes.sharingPolicy,
  appRoutes.cookies,
  appRoutes.staffLogin,
  appRoutes.inviteFriends,
  appRoutes.supportInvite,
  appRoutes.quitPlan,
  appRoutes.cravingCoach,
  appRoutes.relapseSupport,
  appRoutes.safetyGuidance,
  appRoutes.whenToSeekHelp,
  appRoutes.assessment,
  appRoutes.english,
  "/admin",
  "/admin/link-audit",
  "/admin/data-dictionary",
  "/challenges",
  "/city-challenge",
  "/poster-studio",
  "/shop",
  "/training",
  "/volunteer",
]);
