// Aqla Learn — static content (modules + question bank).
// Kept in code for type-safety; admin editing is supported via DB tables for future iterations.

export type Lang = "ar" | "en";

export type LearnQuestion = {
  id: string;
  question_ar: string;
  question_en: string;
  options_ar: string[];
  options_en: string[];
  correct: number;
  explanation_ar: string;
  explanation_en: string;
};

export type LearnModule = {
  slug: string;
  title_ar: string;
  title_en: string;
  subtitle_ar: string;
  subtitle_en: string;
  key_points_ar: string[];
  key_points_en: string[];
  did_you_know_ar: string;
  did_you_know_en: string;
  sources: { label: string; url: string }[];
  questions: LearnQuestion[];
};

const sources = {
  who: { label: "WHO — Tobacco cessation", url: "https://www.who.int/health-topics/tobacco" },
  cdc: { label: "CDC — Quit Smoking", url: "https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/" },
  smokefree: { label: "Smokefree.gov", url: "https://smokefree.gov/" },
  nice: { label: "NICE — Tobacco guideline (NG209)", url: "https://www.nice.org.uk/guidance/ng209" },
  ncsct: { label: "NCSCT — Stop Smoking Resources", url: "https://www.ncsct.co.uk/" },
};

export const LEARN_MODULES: LearnModule[] = [
  {
    slug: "basics",
    title_ar: "أساسيات التدخين والنيكوتين",
    title_en: "Smoking and Nicotine Basics",
    subtitle_ar: "فهم المكونات الأساسية والآثار على الجسم.",
    subtitle_en: "Understand the core substances and their effects on the body.",
    key_points_ar: [
      "النيكوتين هو المادة الرئيسية التي تسبب الاعتماد.",
      "دخان التبغ يحتوي على آلاف المواد الكيميائية، كثير منها ضار.",
      "الإقلاع في أي عمر يحسّن الصحة على المدى القصير والطويل.",
    ],
    key_points_en: [
      "Nicotine is the main substance that drives dependence.",
      "Tobacco smoke contains thousands of chemicals, many harmful.",
      "Quitting at any age improves short- and long-term health.",
    ],
    did_you_know_ar: "خلال 20 دقيقة من آخر سيجارة يبدأ معدل ضربات القلب وضغط الدم بالعودة لمستوى أكثر طبيعية.",
    did_you_know_en: "Within 20 minutes of the last cigarette, heart rate and blood pressure begin returning toward normal.",
    sources: [sources.who, sources.cdc, sources.smokefree],
    questions: [
      {
        id: "basics-1",
        question_ar: "ما المادة الأساسية التي تسبب الاعتماد في منتجات التبغ والنيكوتين؟",
        question_en: "What is the main substance that causes dependence in tobacco and nicotine products?",
        options_ar: ["القطران", "النيكوتين", "أول أكسيد الكربون", "الكافيين"],
        options_en: ["Tar", "Nicotine", "Carbon monoxide", "Caffeine"],
        correct: 1,
        explanation_ar: "النيكوتين يؤثر على دوائر المكافأة في الدماغ ويسبب الاعتماد.",
        explanation_en: "Nicotine affects reward pathways in the brain and drives dependence.",
      },
      {
        id: "basics-2",
        question_ar: "هل الإقلاع عن التدخين يفيد حتى بعد سنوات طويلة من التدخين؟",
        question_en: "Does quitting help even after many years of smoking?",
        options_ar: ["لا فائدة منه", "نعم، يحسن الصحة في أي عمر", "فقط للشباب", "فقط لمن لم يدخن كثيرًا"],
        options_en: ["No benefit", "Yes, it improves health at any age", "Only for younger people", "Only for light smokers"],
        correct: 1,
        explanation_ar: "الإقلاع في أي عمر يقلل خطر الأمراض القلبية والتنفسية.",
        explanation_en: "Quitting at any age lowers the risk of heart and lung disease.",
      },
      {
        id: "basics-3",
        question_ar: "ماذا يبدأ في الجسم خلال 20 دقيقة من آخر سيجارة؟",
        question_en: "What begins in the body within 20 minutes of the last cigarette?",
        options_ar: ["تتجدد الرئتان بالكامل", "يعود معدل ضربات القلب وضغط الدم نحو الطبيعي", "يختفي النيكوتين", "تختفي الرغبة الشديدة فورًا"],
        options_en: ["Lungs fully regenerate", "Heart rate and blood pressure move toward normal", "Nicotine fully clears", "Cravings disappear immediately"],
        correct: 1,
        explanation_ar: "تبدأ تحسنات قلبية وعائية مبكرة جدًا بعد الإقلاع.",
        explanation_en: "Cardiovascular improvements begin very early after quitting.",
      },
      {
        id: "basics-4",
        question_ar: "أيٌّ مما يلي يعتبر منتجًا يحتوي على النيكوتين؟",
        question_en: "Which of the following contains nicotine?",
        options_ar: ["السجائر", "الفيب", "أكياس النيكوتين", "جميع ما سبق"],
        options_en: ["Cigarettes", "Vapes", "Nicotine pouches", "All of the above"],
        correct: 3,
        explanation_ar: "كل هذه المنتجات تحتوي على النيكوتين وقد تسبب الاعتماد.",
        explanation_en: "All of these products contain nicotine and can cause dependence.",
      },
      {
        id: "basics-5",
        question_ar: "هل التدخين \"الخفيف\" آمن صحيًا؟",
        question_en: "Is \"light\" smoking safe?",
        options_ar: ["نعم، آمن تمامًا", "لا، حتى التدخين القليل يزيد المخاطر", "آمن للنساء فقط", "آمن في المساء فقط"],
        options_en: ["Yes, completely safe", "No, even light smoking raises risk", "Safe only for women", "Safe only in the evening"],
        correct: 1,
        explanation_ar: "لا يوجد مستوى آمن للتدخين؛ حتى عدد قليل من السجائر يضر بالصحة.",
        explanation_en: "There is no safe level of smoking; even a few cigarettes harm health.",
      },
      {
        id: "basics-6",
        question_ar: "ما الذي يحدث للرئتين على المدى الطويل بعد الإقلاع؟",
        question_en: "What happens to the lungs long-term after quitting?",
        options_ar: ["تتحسن وظائف الرئة تدريجيًا", "تبقى كما هي تمامًا", "تسوء أكثر", "لا يمكن قياسها"],
        options_en: ["Lung function gradually improves", "Stays exactly the same", "Gets worse", "Cannot be measured"],
        correct: 0,
        explanation_ar: "وظائف الرئة تتحسن مع الوقت بعد الإقلاع.",
        explanation_en: "Lung function gradually improves over time after quitting.",
      },
      {
        id: "basics-7",
        question_ar: "هل الإقلاع المفاجئ ممكن وآمن لمعظم الناس؟",
        question_en: "Is sudden quitting possible and safe for most people?",
        options_ar: ["نعم، مع وجود خطة ودعم", "لا، يجب التقليل التدريجي فقط", "خطير جدًا", "مستحيل دون أدوية"],
        options_en: ["Yes, with a plan and support", "No, only gradual reduction works", "Very dangerous", "Impossible without medication"],
        correct: 0,
        explanation_ar: "كثير من الناس ينجحون بالإقلاع المفاجئ مع الدعم المناسب.",
        explanation_en: "Many people quit successfully cold-turkey with proper support.",
      },
    ],
  },
  {
    slug: "dependence",
    title_ar: "كيف يحدث الاعتماد على النيكوتين؟",
    title_en: "How Nicotine Dependence Happens",
    subtitle_ar: "آلية الاعتماد وعلامات الانسحاب.",
    subtitle_en: "How dependence forms and what withdrawal looks like.",
    key_points_ar: [
      "النيكوتين يحفز إفراز الدوبامين في دوائر المكافأة.",
      "الانسحاب قد يشمل القلق والتركيز الضعيف والرغبة الشديدة.",
      "أعراض الانسحاب مؤقتة وتقل خلال أسابيع.",
    ],
    key_points_en: [
      "Nicotine triggers dopamine release in reward circuits.",
      "Withdrawal may include irritability, poor focus, and cravings.",
      "Withdrawal symptoms are temporary and ease within weeks.",
    ],
    did_you_know_ar: "معظم أعراض الانسحاب الجسدية تبلغ ذروتها خلال أول أسبوع وتخف بسرعة.",
    did_you_know_en: "Most physical withdrawal symptoms peak within the first week and ease quickly.",
    sources: [sources.ncsct, sources.nice, sources.cdc],
    questions: [
      {
        id: "dep-1",
        question_ar: "كم تستمر معظم أعراض الانسحاب الجسدية؟",
        question_en: "How long do most physical withdrawal symptoms typically last?",
        options_ar: ["سنوات", "أيام إلى أسابيع قليلة", "ساعات فقط", "لا تنتهي أبدًا"],
        options_en: ["Years", "Days to a few weeks", "Only hours", "They never end"],
        correct: 1,
        explanation_ar: "تبلغ الذروة في الأسبوع الأول ثم تتراجع تدريجيًا.",
        explanation_en: "They peak in the first week and then taper.",
      },
      {
        id: "dep-2",
        question_ar: "ما الناقل العصبي الذي يحفزه النيكوتين بشكل رئيسي؟",
        question_en: "Which neurotransmitter does nicotine mainly trigger?",
        options_ar: ["الدوبامين", "الميلاتونين", "الكورتيزول", "الإنسولين"],
        options_en: ["Dopamine", "Melatonin", "Cortisol", "Insulin"],
        correct: 0,
        explanation_ar: "إفراز الدوبامين يعزز سلوك الاستخدام المتكرر.",
        explanation_en: "Dopamine release reinforces repeated use.",
      },
      {
        id: "dep-3",
        question_ar: "أيٌّ مما يلي قد يكون عرضًا للانسحاب؟",
        question_en: "Which can be a withdrawal symptom?",
        options_ar: ["زيادة الطاقة", "تهيج، قلق، صعوبة تركيز", "تحسن نوم فوري", "اختفاء الجوع"],
        options_en: ["Increased energy", "Irritability, anxiety, poor focus", "Instant better sleep", "Loss of appetite forever"],
        correct: 1,
        explanation_ar: "هذه أعراض شائعة ومؤقتة.",
        explanation_en: "These are common and temporary symptoms.",
      },
      {
        id: "dep-4",
        question_ar: "هل الاعتماد على النيكوتين علامة ضعف شخصية؟",
        question_en: "Is nicotine dependence a sign of weak willpower?",
        options_ar: ["نعم", "لا، هو اعتماد فسيولوجي وسلوكي", "فقط لكبار السن", "فقط للمبتدئين"],
        options_en: ["Yes", "No, it is physiological and behavioral", "Only in older adults", "Only in beginners"],
        correct: 1,
        explanation_ar: "الاعتماد ظاهرة بيولوجية وسلوكية، وليس ضعفًا.",
        explanation_en: "Dependence is biological and behavioral, not weakness.",
      },
      {
        id: "dep-5",
        question_ar: "هل يمكن أن يقلل الدعم السلوكي من شدة الرغبة؟",
        question_en: "Can behavioral support reduce craving intensity?",
        options_ar: ["لا تأثير له", "نعم، يساعد بشكل كبير", "يزيدها", "فقط مع الأدوية"],
        options_en: ["No effect", "Yes, it helps significantly", "Makes it worse", "Only with medication"],
        correct: 1,
        explanation_ar: "الدعم السلوكي مهم ومثبت علميًا.",
        explanation_en: "Behavioral support is important and evidence-based.",
      },
      {
        id: "dep-6",
        question_ar: "هل النيكوتين أكثر إدمانًا عند بدء استخدامه في عمر صغير؟",
        question_en: "Is nicotine more addictive when use starts at a young age?",
        options_ar: ["لا فرق", "نعم، الدماغ النامي أكثر عرضة", "أقل إدمانًا", "آمن تمامًا للصغار"],
        options_en: ["No difference", "Yes, the developing brain is more vulnerable", "Less addictive", "Completely safe for youth"],
        correct: 1,
        explanation_ar: "الدماغ النامي أكثر حساسية لتأثيرات النيكوتين.",
        explanation_en: "The developing brain is more sensitive to nicotine.",
      },
      {
        id: "dep-7",
        question_ar: "متى يبدأ الجسم بالتعافي من اعتماد النيكوتين؟",
        question_en: "When does the body begin recovering from nicotine dependence?",
        options_ar: ["لا يتعافى أبدًا", "خلال أيام إلى أسابيع من الإقلاع", "بعد سنوات فقط", "فقط في المستشفى"],
        options_en: ["Never", "Within days to weeks of quitting", "Only after many years", "Only in hospital"],
        correct: 1,
        explanation_ar: "التعافي يبدأ خلال أيام والمستقبلات تعود لتوازنها تدريجيًا.",
        explanation_en: "Recovery starts within days as receptors rebalance.",
      },
    ],
  },
  {
    slug: "vaping",
    title_ar: "السجائر الإلكترونية والفيب",
    title_en: "Vaping and E-Cigarettes",
    subtitle_ar: "ما تعرفه وما لا تعرفه عن الفيب.",
    subtitle_en: "What we know and what we do not yet know about vaping.",
    key_points_ar: [
      "أغلب أجهزة الفيب تحتوي على نيكوتين، أحيانًا بتركيز عالٍ.",
      "الفيب ليس \"بخار ماء\"؛ بل أيروسول يحتوي على مواد كيميائية.",
      "السلامة طويلة المدى لا تزال قيد الدراسة.",
    ],
    key_points_en: [
      "Most vapes contain nicotine, sometimes in high concentrations.",
      "Vape \"clouds\" are aerosols containing chemicals, not water vapor.",
      "Long-term safety is still being studied.",
    ],
    did_you_know_ar: "بعض أجهزة الفيب تحتوي على نيكوتين يعادل عبوة سجائر كاملة في جهاز واحد.",
    did_you_know_en: "Some disposable vapes contain nicotine equivalent to a whole pack of cigarettes in one device.",
    sources: [sources.who, sources.cdc],
    questions: [
      {
        id: "vape-1",
        question_ar: "هل ما يخرج من جهاز الفيب هو \"بخار ماء\" فقط؟",
        question_en: "Is what comes out of a vape just \"water vapor\"?",
        options_ar: ["نعم", "لا، هو أيروسول يحتوي على مواد كيميائية", "هو دخان عادي", "لا يحتوي على نيكوتين أبدًا"],
        options_en: ["Yes", "No, it is an aerosol with chemicals", "It is just smoke", "It never contains nicotine"],
        correct: 1,
        explanation_ar: "الفيب يطلق أيروسول يحوي نيكوتين ومواد إضافية.",
        explanation_en: "Vaping emits an aerosol containing nicotine and other compounds.",
      },
      {
        id: "vape-2",
        question_ar: "هل يمكن أن يسبب الفيب اعتمادًا على النيكوتين؟",
        question_en: "Can vaping cause nicotine dependence?",
        options_ar: ["لا أبدًا", "نعم، خصوصًا بتركيزات النيكوتين العالية", "فقط للمراهقين", "فقط مع النكهات"],
        options_en: ["Never", "Yes, especially with high nicotine concentrations", "Only in teens", "Only with flavors"],
        correct: 1,
        explanation_ar: "الفيب الحديث قد يحتوي على نيكوتين عالٍ يسبب اعتمادًا سريعًا.",
        explanation_en: "Modern vapes can deliver high nicotine doses causing rapid dependence.",
      },
      {
        id: "vape-3",
        question_ar: "هل الفيب بديل آمن تمامًا للسجائر؟",
        question_en: "Is vaping a completely safe alternative to cigarettes?",
        options_ar: ["نعم", "لا، السلامة طويلة المدى غير مؤكدة", "آمن للأطفال", "آمن للحوامل"],
        options_en: ["Yes", "No, long-term safety is not established", "Safe for children", "Safe in pregnancy"],
        correct: 1,
        explanation_ar: "لا يعتبر آمنًا تمامًا، ويُمنع للحوامل والأطفال.",
        explanation_en: "Not considered safe; not for pregnancy or youth.",
      },
      {
        id: "vape-4",
        question_ar: "ماذا يجب على غير المدخن أن يفعل تجاه الفيب؟",
        question_en: "What should a non-smoker do regarding vaping?",
        options_ar: ["تجربته", "تجنبه", "استخدامه للتسلية", "استخدامه لتحسين النوم"],
        options_en: ["Try it", "Avoid it", "Use it for fun", "Use it to improve sleep"],
        correct: 1,
        explanation_ar: "الفيب ليس مخصصًا لغير المدخنين.",
        explanation_en: "Vaping is not intended for non-smokers.",
      },
      {
        id: "vape-5",
        question_ar: "هل يحتوي الفيب على نكهات قد تجذب اليافعين؟",
        question_en: "Do vapes have flavors that may appeal to youth?",
        options_ar: ["نعم", "لا", "فقط نكهة التبغ", "نكهة الماء فقط"],
        options_en: ["Yes", "No", "Only tobacco flavor", "Only water"],
        correct: 0,
        explanation_ar: "النكهات الحلوة تشكل مصدر قلق صحي عام.",
        explanation_en: "Sweet flavors are a public-health concern for youth uptake.",
      },
      {
        id: "vape-6",
        question_ar: "ما الأفضل لمن يريد الإقلاع عن السجائر؟",
        question_en: "What is best for someone who wants to quit cigarettes?",
        options_ar: ["التحول للفيب فقط دون متابعة", "خطة إقلاع وأدوات مدعومة بالأدلة وتقييم مختص", "زيادة عدد السجائر", "تجاهل الموضوع"],
        options_en: ["Just switch to vaping without follow-up", "Evidence-based plan, tools, and a clinician check", "Smoking more cigarettes", "Ignoring the issue"],
        correct: 1,
        explanation_ar: "الخطة المدعومة بالأدلة والمتابعة هي الأكثر فعالية.",
        explanation_en: "Evidence-based planning with follow-up is most effective.",
      },
      {
        id: "vape-7",
        question_ar: "هل الفيب آمن أثناء الحمل؟",
        question_en: "Is vaping safe during pregnancy?",
        options_ar: ["نعم", "لا، يُنصح بتجنبه", "آمن في الثلث الأول", "آمن في الثلث الأخير"],
        options_en: ["Yes", "No, it should be avoided", "Safe in first trimester", "Safe in last trimester"],
        correct: 1,
        explanation_ar: "النيكوتين يضر بنمو الجنين.",
        explanation_en: "Nicotine harms fetal development.",
      },
    ],
  },
  {
    slug: "pouches",
    title_ar: "أكياس النيكوتين",
    title_en: "Nicotine Pouches",
    subtitle_ar: "ماذا تحتوي وما مخاطرها؟",
    subtitle_en: "What they contain and what to watch for.",
    key_points_ar: [
      "تحتوي على نيكوتين بتركيزات متفاوتة وقد تكون مرتفعة.",
      "قد تسبب تهيج اللثة ومشاكل في الفم.",
      "يمكن أن تسبب اعتمادًا سريعًا.",
    ],
    key_points_en: [
      "They contain nicotine in varying, sometimes high, strengths.",
      "May irritate gums and cause mouth problems.",
      "Can cause rapid dependence.",
    ],
    did_you_know_ar: "بعض الأكياس تحرر النيكوتين بسرعة، مما يجعل الاعتماد عليها سهل التطور.",
    did_you_know_en: "Some pouches deliver nicotine quickly, making dependence easy to develop.",
    sources: [sources.who, sources.cdc],
    questions: [
      {
        id: "pouch-1",
        question_ar: "هل تحتوي أكياس النيكوتين على النيكوتين؟",
        question_en: "Do nicotine pouches contain nicotine?",
        options_ar: ["لا", "نعم، وبتركيزات متفاوتة", "فقط على نكهات", "فقط على ألياف"],
        options_en: ["No", "Yes, at varying strengths", "Only flavors", "Only fibers"],
        correct: 1,
        explanation_ar: "كميات النيكوتين تتفاوت بشكل كبير بين المنتجات.",
        explanation_en: "Nicotine amounts vary widely between products.",
      },
      {
        id: "pouch-2",
        question_ar: "ما العَرَض الذي قد يظهر في الفم؟",
        question_en: "What mouth symptom can appear?",
        options_ar: ["تحسن حاسة التذوق", "تهيج اللثة أو الفم", "تبيض الأسنان فورًا", "اختفاء التسوس"],
        options_en: ["Improved taste", "Gum or mouth irritation", "Instant teeth whitening", "Disappearance of cavities"],
        correct: 1,
        explanation_ar: "التهيج وتراجع اللثة من الآثار الشائعة.",
        explanation_en: "Irritation and gum recession are common effects.",
      },
      {
        id: "pouch-3",
        question_ar: "هل أكياس النيكوتين خالية تمامًا من المخاطر؟",
        question_en: "Are pouches risk-free?",
        options_ar: ["نعم", "لا، توجد مخاطر ومخاوف صحية", "آمنة للأطفال", "آمنة في الحمل"],
        options_en: ["Yes", "No, there are risks and health concerns", "Safe for children", "Safe in pregnancy"],
        correct: 1,
        explanation_ar: "ليست خالية من المخاطر، خصوصًا للنيكوتين العالي.",
        explanation_en: "Not risk-free, especially with high nicotine strengths.",
      },
      {
        id: "pouch-4",
        question_ar: "هل يمكن أن تسبب الأكياس اعتمادًا؟",
        question_en: "Can pouches cause dependence?",
        options_ar: ["لا", "نعم، قد تسبب اعتمادًا سريعًا", "فقط مع الاستخدام لسنوات", "فقط للنساء"],
        options_en: ["No", "Yes, dependence can develop quickly", "Only after years", "Only in women"],
        correct: 1,
        explanation_ar: "النيكوتين السريع الامتصاص يعزز الاعتماد.",
        explanation_en: "Fast nicotine absorption promotes dependence.",
      },
      {
        id: "pouch-5",
        question_ar: "ماذا تفعل إذا لاحظت تقرحات أو ألمًا متكررًا في الفم؟",
        question_en: "What should you do if you notice mouth ulcers or persistent pain?",
        options_ar: ["زيادة الاستخدام", "إيقاف المنتج ومراجعة مختص", "تجاهل الأمر", "تغيير النكهة فقط"],
        options_en: ["Use more", "Stop and consult a clinician", "Ignore it", "Just change flavor"],
        correct: 1,
        explanation_ar: "الأعراض المستمرة تستدعي تقييمًا طبيًا.",
        explanation_en: "Persistent symptoms warrant medical evaluation.",
      },
      {
        id: "pouch-6",
        question_ar: "هل تركيز النيكوتين متشابه بين جميع الأكياس؟",
        question_en: "Is nicotine strength similar across all pouches?",
        options_ar: ["نعم", "لا، يتفاوت بشكل كبير", "كلها منخفضة", "كلها مرتفعة"],
        options_en: ["Yes", "No, it varies widely", "All low", "All high"],
        correct: 1,
        explanation_ar: "اقرأ الملصق لمعرفة التركيز.",
        explanation_en: "Read the label to know the strength.",
      },
      {
        id: "pouch-7",
        question_ar: "هل تحل الأكياس محل الإقلاع التام؟",
        question_en: "Do pouches replace fully quitting?",
        options_ar: ["نعم، حل دائم", "لا، الإقلاع الكامل هو الهدف الأكثر فائدة", "لا حاجة للإقلاع", "تحل محل الفيب فقط"],
        options_en: ["Yes, a permanent solution", "No, full quitting is the most beneficial goal", "No need to quit", "They only replace vaping"],
        correct: 1,
        explanation_ar: "الإقلاع الكامل من النيكوتين هو الهدف الأكثر فائدة على المدى الطويل.",
        explanation_en: "Full nicotine cessation offers the greatest long-term benefit.",
      },
    ],
  },
  {
    slug: "shisha",
    title_ar: "الشيشة والمعسل",
    title_en: "Shisha and Hookah",
    subtitle_ar: "خرافات وحقائق حول الشيشة.",
    subtitle_en: "Myths and facts about hookah.",
    key_points_ar: [
      "جلسة شيشة واحدة قد تعرّضك لكميات كبيرة من الدخان والمواد الضارة.",
      "الماء لا يفلتر النيكوتين أو المواد السامة.",
      "مشاركة الفم مع آخرين قد تنقل العدوى.",
    ],
    key_points_en: [
      "One hookah session can expose you to large amounts of smoke and harmful chemicals.",
      "Water does not filter nicotine or toxins.",
      "Sharing mouthpieces can transmit infections.",
    ],
    did_you_know_ar: "جلسة شيشة واحدة قد تعادل التعرض لدخان عشرات السجائر من حيث الكمية المستنشقة.",
    did_you_know_en: "A single hookah session can equal inhaling dozens of cigarettes' worth of smoke by volume.",
    sources: [sources.who, sources.cdc],
    questions: [
      {
        id: "sh-1",
        question_ar: "هل الماء في الشيشة يفلتر النيكوتين والمواد الضارة؟",
        question_en: "Does the water in a hookah filter out nicotine and harmful chemicals?",
        options_ar: ["نعم تمامًا", "لا، لا يفلترها", "يفلتر نصفها", "يفلتر النكهة فقط"],
        options_en: ["Yes, completely", "No, it does not filter them", "Filters half", "Filters only flavor"],
        correct: 1,
        explanation_ar: "الماء لا يحمي من المواد السامة في الدخان.",
        explanation_en: "Water does not protect from toxic compounds in smoke.",
      },
      {
        id: "sh-2",
        question_ar: "هل الشيشة أقل ضررًا من السجائر؟",
        question_en: "Is hookah less harmful than cigarettes?",
        options_ar: ["نعم بكثير", "لا، قد تكون مساوية أو أكثر تعرضًا في الجلسة", "مفيدة للرئة", "لا تحتوي على نيكوتين"],
        options_en: ["Yes, much less", "No, exposure can equal or exceed cigarettes per session", "Good for lungs", "Has no nicotine"],
        correct: 1,
        explanation_ar: "كمية الدخان المستنشقة في جلسة شيشة كبيرة.",
        explanation_en: "The amount of smoke inhaled in a hookah session is large.",
      },
      {
        id: "sh-3",
        question_ar: "هل مشاركة قطعة الفم آمنة؟",
        question_en: "Is sharing the mouthpiece safe?",
        options_ar: ["نعم", "لا، قد تنقل العدوى", "آمنة مع الأصدقاء فقط", "آمنة بعد المسح"],
        options_en: ["Yes", "No, it can transmit infections", "Safe only with friends", "Safe after wiping"],
        correct: 1,
        explanation_ar: "ينصح بعدم مشاركة قطعة الفم.",
        explanation_en: "Sharing mouthpieces is not recommended.",
      },
      {
        id: "sh-4",
        question_ar: "هل تحتوي الشيشة على أول أكسيد الكربون؟",
        question_en: "Does hookah smoke contain carbon monoxide?",
        options_ar: ["لا", "نعم، بكميات قد تكون مرتفعة", "فقط الفحم", "لا أحد يعرف"],
        options_en: ["No", "Yes, sometimes in high amounts", "Only the charcoal", "Nobody knows"],
        correct: 1,
        explanation_ar: "أول أكسيد الكربون من الفحم خطر معروف.",
        explanation_en: "Carbon monoxide from charcoal is a known hazard.",
      },
      {
        id: "sh-5",
        question_ar: "هل النكهات تعني أن الدخان صحي؟",
        question_en: "Do flavors mean the smoke is healthy?",
        options_ar: ["نعم", "لا، النكهة لا تلغي الضرر", "النكهات مفيدة", "النكهات مياه فقط"],
        options_en: ["Yes", "No, flavor does not remove harm", "Flavors are beneficial", "Flavors are just water"],
        correct: 1,
        explanation_ar: "النكهات لا تلغي السمية.",
        explanation_en: "Flavors do not remove toxicity.",
      },
      {
        id: "sh-6",
        question_ar: "هل يمكن للشيشة أن تسبب اعتمادًا على النيكوتين؟",
        question_en: "Can hookah cause nicotine dependence?",
        options_ar: ["لا", "نعم", "فقط للمدخنين السابقين", "فقط في المساء"],
        options_en: ["No", "Yes", "Only for ex-smokers", "Only in the evening"],
        correct: 1,
        explanation_ar: "المعسل يحتوي على نيكوتين.",
        explanation_en: "Hookah tobacco contains nicotine.",
      },
      {
        id: "sh-7",
        question_ar: "ما الأكثر فعالية للحد من الضرر؟",
        question_en: "What is most effective to reduce harm?",
        options_ar: ["تقليل الجلسات فقط", "الإقلاع الكامل عن جميع منتجات التبغ", "تغيير النكهة", "التدخين سريعًا"],
        options_en: ["Cut sessions only", "Quit all tobacco products completely", "Change flavor", "Smoke faster"],
        correct: 1,
        explanation_ar: "الإقلاع الكامل هو الأكثر فعالية.",
        explanation_en: "Full cessation is most effective.",
      },
    ],
  },
  {
    slug: "triggers",
    title_ar: "المحفزات والرغبة الشديدة",
    title_en: "Triggers and Cravings",
    subtitle_ar: "كيف تتعرف على محفزاتك وتتعامل معها.",
    subtitle_en: "Identify triggers and respond to cravings.",
    key_points_ar: [
      "معظم الرغبات الشديدة تستمر 3 إلى 5 دقائق فقط.",
      "تغيير المكان والنشاط يساعد على تجاوز الرغبة.",
      "تأجيل القرار خمس دقائق غالبًا ينجح.",
    ],
    key_points_en: [
      "Most cravings last only 3 to 5 minutes.",
      "Changing place and activity helps you ride out the urge.",
      "Delaying the decision for 5 minutes often works.",
    ],
    did_you_know_ar: "الرغبة الشديدة تشبه الموجة: ترتفع وتنخفض، ولا تستمر طويلًا.",
    did_you_know_en: "A craving is like a wave: it rises and falls, and does not last long.",
    sources: [sources.smokefree, sources.ncsct],
    questions: [
      {
        id: "tr-1",
        question_ar: "ما التصرف الأفضل عند حدوث رغبة شديدة مفاجئة؟",
        question_en: "What is a helpful first step when a strong craving appears?",
        options_ar: ["الاستسلام مباشرة", "تأجيل الرغبة لبضع دقائق وتغيير المكان", "زيادة الاستخدام", "تجاهل الخطة تمامًا"],
        options_en: ["Give in immediately", "Delay for a few minutes and change location", "Use more nicotine", "Ignore the plan completely"],
        correct: 1,
        explanation_ar: "التأجيل وتغيير السياق يقللان شدة الرغبة.",
        explanation_en: "Delay and context change reduce craving intensity.",
      },
      {
        id: "tr-2",
        question_ar: "كم تستمر الرغبة الشديدة عادة؟",
        question_en: "How long does a strong craving usually last?",
        options_ar: ["ساعات", "3-5 دقائق", "يوم كامل", "أسبوع"],
        options_en: ["Hours", "3-5 minutes", "A full day", "A week"],
        correct: 1,
        explanation_ar: "الرغبة موجة قصيرة تمر بسرعة.",
        explanation_en: "Cravings are short waves that pass quickly.",
      },
      {
        id: "tr-3",
        question_ar: "ما المثال على المحفز السلوكي؟",
        question_en: "Which is an example of a behavioral trigger?",
        options_ar: ["شرب القهوة", "كل ما سبق", "الإجهاد", "وقت معين من اليوم"],
        options_en: ["Drinking coffee", "All of the above", "Stress", "A certain time of day"],
        correct: 1,
        explanation_ar: "كل هذه محفزات شائعة.",
        explanation_en: "All of these are common triggers.",
      },
      {
        id: "tr-4",
        question_ar: "هل التنفس العميق يساعد على تجاوز الرغبة؟",
        question_en: "Can deep breathing help ride out a craving?",
        options_ar: ["لا فائدة", "نعم، يساعد", "يزيد الرغبة", "يسبب دوارًا فقط"],
        options_en: ["No effect", "Yes, it helps", "Makes it worse", "Only causes dizziness"],
        correct: 1,
        explanation_ar: "التنفس البطيء يهدئ الجهاز العصبي.",
        explanation_en: "Slow breathing calms the nervous system.",
      },
      {
        id: "tr-5",
        question_ar: "هل شرب الماء قد يساعد في تخفيف الرغبة؟",
        question_en: "Can drinking water help ease cravings?",
        options_ar: ["لا", "نعم، خطوة بسيطة وفعالة", "يزيدها", "خطر"],
        options_en: ["No", "Yes, a simple effective step", "Makes it worse", "Dangerous"],
        correct: 1,
        explanation_ar: "الماء يكسر الروتين ويعطي بديلًا فوريًا.",
        explanation_en: "Water interrupts the routine and provides a quick substitute.",
      },
      {
        id: "tr-6",
        question_ar: "ما الأفضل: مقاومة الرغبة وحدك أم طلب الدعم؟",
        question_en: "Is it better to resist cravings alone or seek support?",
        options_ar: ["وحدك دائمًا", "الدعم يساعد كثيرًا", "تجاهلها فقط", "لا فرق"],
        options_en: ["Always alone", "Support helps a lot", "Just ignore them", "No difference"],
        correct: 1,
        explanation_ar: "الدعم الاجتماعي يرفع نسب النجاح.",
        explanation_en: "Social support improves success rates.",
      },
      {
        id: "tr-7",
        question_ar: "هل التعرف على المحفزات مسبقًا يفيد؟",
        question_en: "Does identifying triggers in advance help?",
        options_ar: ["لا", "نعم، يساعد على بناء خطة", "يفاقم الوضع", "لا علاقة له"],
        options_en: ["No", "Yes, it helps you build a plan", "Makes things worse", "Unrelated"],
        correct: 1,
        explanation_ar: "خرائط المحفزات أداة فعالة في الإقلاع.",
        explanation_en: "Trigger mapping is an effective cessation tool.",
      },
    ],
  },
  {
    slug: "relapse",
    title_ar: "الانتكاسة ليست فشلًا",
    title_en: "Relapse Is Not Failure",
    subtitle_ar: "كيف تتعامل مع الانتكاسة بإيجابية.",
    subtitle_en: "How to handle a relapse constructively.",
    key_points_ar: [
      "كثير من الناس يحتاجون عدة محاولات قبل الإقلاع النهائي.",
      "الانتكاسة فرصة لتعلم ما الذي يحتاج تعديلًا.",
      "العودة السريعة إلى الخطة أهم من الكمال.",
    ],
    key_points_en: [
      "Many people need several attempts before quitting for good.",
      "Relapse is a chance to learn what needs adjustment.",
      "Returning quickly to the plan matters more than perfection.",
    ],
    did_you_know_ar: "كل محاولة إقلاع تزيد فرصة النجاح في المرات القادمة.",
    did_you_know_en: "Every quit attempt increases the chance of success on later attempts.",
    sources: [sources.ncsct, sources.smokefree],
    questions: [
      {
        id: "rel-1",
        question_ar: "ماذا تعني الانتكاسة غالبًا؟",
        question_en: "What does relapse usually mean?",
        options_ar: ["فشل كامل", "أن الشخص لا يستطيع الإقلاع أبدًا", "أن الخطة تحتاج مراجعة ودعمًا إضافيًا", "أن الإقلاع غير ممكن"],
        options_en: ["Complete failure", "The person can never quit", "The plan may need review and more support", "Quitting is impossible"],
        correct: 2,
        explanation_ar: "الانتكاسة جزء طبيعي من رحلة كثير من الناس.",
        explanation_en: "Relapse is a normal part of many people's journeys.",
      },
      {
        id: "rel-2",
        question_ar: "ما الأفضل بعد الانتكاسة؟",
        question_en: "What is best after a relapse?",
        options_ar: ["التوقف عن المحاولة", "العودة للخطة سريعًا وطلب الدعم", "زيادة التدخين", "الشعور بالذنب طويلًا"],
        options_en: ["Stop trying", "Return to the plan quickly and seek support", "Smoke more", "Stay in guilt for long"],
        correct: 1,
        explanation_ar: "العودة السريعة تحفظ التقدم.",
        explanation_en: "Returning quickly preserves progress.",
      },
      {
        id: "rel-3",
        question_ar: "هل المحاولات السابقة \"تذهب سدى\"؟",
        question_en: "Do previous attempts \"go to waste\"?",
        options_ar: ["نعم", "لا، كل محاولة تعلّم", "أحيانًا", "لا أحد يعرف"],
        options_en: ["Yes", "No, every attempt teaches you", "Sometimes", "Nobody knows"],
        correct: 1,
        explanation_ar: "كل محاولة تبني خبرة قابلة للاستخدام لاحقًا.",
        explanation_en: "Each attempt builds usable experience.",
      },
      {
        id: "rel-4",
        question_ar: "هل الانتكاسة مدعاة للوم النفس بقسوة؟",
        question_en: "Is relapse a reason for harsh self-blame?",
        options_ar: ["نعم", "لا، التعامل اللطيف مع النفس أفضل", "لا تأثير له", "كله نفسي"],
        options_en: ["Yes", "No, self-compassion works better", "No effect", "It is all mental"],
        correct: 1,
        explanation_ar: "اللوم القاسي قد يطيل مدة الانتكاسة.",
        explanation_en: "Harsh self-blame can prolong relapse.",
      },
      {
        id: "rel-5",
        question_ar: "أيٌّ مما يلي يقلل خطر الانتكاسة؟",
        question_en: "Which lowers the risk of relapse?",
        options_ar: ["تجاهل المحفزات", "خطة مكتوبة + دعم + متابعة", "العزلة", "زيادة الإجهاد"],
        options_en: ["Ignoring triggers", "Written plan + support + follow-up", "Isolation", "More stress"],
        correct: 1,
        explanation_ar: "العناصر الثلاثة مهمة معًا.",
        explanation_en: "All three elements matter together.",
      },
      {
        id: "rel-6",
        question_ar: "هل التحدث مع متطوع أو مختص بعد الانتكاسة مفيد؟",
        question_en: "Is talking to a volunteer or clinician after relapse helpful?",
        options_ar: ["لا", "نعم", "فقط في المستشفى", "فقط للأصدقاء"],
        options_en: ["No", "Yes", "Only in a hospital", "Only with friends"],
        correct: 1,
        explanation_ar: "الدعم يقلل الشعور بالعزلة ويعزز الخطة.",
        explanation_en: "Support reduces isolation and strengthens the plan.",
      },
      {
        id: "rel-7",
        question_ar: "هل الإقلاع \"مرة واحدة وللأبد\" مطلب واقعي؟",
        question_en: "Is \"one-and-done\" quitting always realistic?",
        options_ar: ["نعم للجميع", "ليس بالضرورة؛ كثير يحتاجون محاولات", "فقط للرجال", "فقط لكبار السن"],
        options_en: ["Yes for everyone", "Not necessarily; many need multiple attempts", "Only for men", "Only for older adults"],
        correct: 1,
        explanation_ar: "المحاولات المتعددة شائعة جدًا.",
        explanation_en: "Multiple attempts are very common.",
      },
    ],
  },
  {
    slug: "secondhand",
    title_ar: "التدخين السلبي",
    title_en: "Secondhand Smoke",
    subtitle_ar: "أثر الدخان على من حولك.",
    subtitle_en: "How smoke affects the people around you.",
    key_points_ar: [
      "التدخين السلبي يضر الأطفال والحوامل بشكل خاص.",
      "لا يوجد مستوى آمن من التعرض لدخان التبغ.",
      "البيئات الخالية من التدخين تحمي الجميع.",
    ],
    key_points_en: [
      "Secondhand smoke especially harms children and pregnant women.",
      "There is no safe level of exposure to tobacco smoke.",
      "Smoke-free environments protect everyone.",
    ],
    did_you_know_ar: "أبخرة التدخين تبقى في الملابس والأثاث وتُسمى \"التدخين الثالث\".",
    did_you_know_en: "Smoke residue lingers on clothes and furniture — known as \"thirdhand smoke\".",
    sources: [sources.who, sources.cdc],
    questions: [
      {
        id: "sec-1",
        question_ar: "هل التدخين السلبي يضر الأطفال؟",
        question_en: "Does secondhand smoke harm children?",
        options_ar: ["لا", "نعم بشكل واضح", "فقط الذكور", "فقط في الصيف"],
        options_en: ["No", "Yes, clearly", "Only boys", "Only in summer"],
        correct: 1,
        explanation_ar: "الأطفال أكثر حساسية لمواد الدخان.",
        explanation_en: "Children are more sensitive to smoke chemicals.",
      },
      {
        id: "sec-2",
        question_ar: "هل التدخين قرب نافذة مفتوحة يلغي خطر التدخين السلبي؟",
        question_en: "Does smoking by an open window eliminate secondhand-smoke risk?",
        options_ar: ["نعم", "لا، يبقى التعرض قائمًا", "يقلله نصفًا", "يلغيه كليًا"],
        options_en: ["Yes", "No, exposure remains", "Halves it", "Eliminates it"],
        correct: 1,
        explanation_ar: "بقايا الدخان تنتشر داخل المنزل وعلى الأقمشة.",
        explanation_en: "Smoke residue spreads indoors and on fabrics.",
      },
      {
        id: "sec-3",
        question_ar: "ما \"التدخين الثالث\"؟",
        question_en: "What is \"thirdhand smoke\"?",
        options_ar: ["دخان قديم في الهواء", "بقايا الدخان على الأسطح والملابس", "نوع جديد من الفيب", "عطر التبغ"],
        options_en: ["Old smoke in the air", "Smoke residue on surfaces and clothes", "A new vape", "Tobacco fragrance"],
        correct: 1,
        explanation_ar: "البقايا الكيميائية تبقى لفترات طويلة.",
        explanation_en: "Chemical residue lingers for long periods.",
      },
      {
        id: "sec-4",
        question_ar: "هل توجد كمية آمنة من التدخين السلبي؟",
        question_en: "Is there a safe amount of secondhand smoke?",
        options_ar: ["نعم", "لا", "للأصحاء فقط", "للبالغين فقط"],
        options_en: ["Yes", "No", "Only for healthy people", "Only for adults"],
        correct: 1,
        explanation_ar: "لا يوجد مستوى آمن للتعرض.",
        explanation_en: "There is no safe level of exposure.",
      },
      {
        id: "sec-5",
        question_ar: "ما الأفضل لحماية الأسرة؟",
        question_en: "What is best to protect the family?",
        options_ar: ["التدخين في غرفة منفصلة", "بيئة خالية تمامًا من التدخين", "التدخين في الحمام", "زيادة التهوية فقط"],
        options_en: ["Smoking in a separate room", "A fully smoke-free environment", "Smoking in the bathroom", "Just adding ventilation"],
        correct: 1,
        explanation_ar: "الحل الفعّال هو بيئة خالية من التدخين.",
        explanation_en: "An effective solution is a fully smoke-free environment.",
      },
      {
        id: "sec-6",
        question_ar: "هل التدخين السلبي يضر الحوامل؟",
        question_en: "Does secondhand smoke harm pregnant women?",
        options_ar: ["لا", "نعم", "فقط في الشهر الأول", "فقط الذكور من الأجنة"],
        options_en: ["No", "Yes", "Only in first month", "Only male fetuses"],
        correct: 1,
        explanation_ar: "التعرض قد يؤثر على نمو الجنين.",
        explanation_en: "Exposure can affect fetal development.",
      },
      {
        id: "sec-7",
        question_ar: "هل التدخين خارج المنزل يلغي التعرض داخل المنزل؟",
        question_en: "Does smoking outside eliminate indoor exposure?",
        options_ar: ["نعم", "لا، تبقى بقايا على الملابس", "أحيانًا فقط", "نعم بعد ساعة"],
        options_en: ["Yes", "No, residue stays on clothing", "Only sometimes", "Yes after one hour"],
        correct: 1,
        explanation_ar: "البقايا تنتقل مع الملابس والشعر.",
        explanation_en: "Residue transfers via clothing and hair.",
      },
    ],
  },
  {
    slug: "support",
    title_ar: "كيف تساعد شخصًا يريد الإقلاع؟",
    title_en: "How to Support Someone Who Wants to Quit",
    subtitle_ar: "كن داعمًا بدون ضغط أو لوم.",
    subtitle_en: "Be supportive without pressure or blame.",
    key_points_ar: [
      "الاستماع أهم من إعطاء المحاضرات.",
      "تشجيع الخطوات الصغيرة فعّال.",
      "احترم خياراته ولا تستخدم اللوم.",
    ],
    key_points_en: [
      "Listening matters more than lecturing.",
      "Encouraging small steps is effective.",
      "Respect their choices and avoid blame.",
    ],
    did_you_know_ar: "وجود شخص داعم يضاعف فرص نجاح الإقلاع.",
    did_you_know_en: "Having a supportive person can double the chance of successful quitting.",
    sources: [sources.ncsct, sources.smokefree],
    questions: [
      {
        id: "sup-1",
        question_ar: "ما أفضل طريقة لمساعدة شخص يريد الإقلاع؟",
        question_en: "What is a helpful way to support someone who wants to quit?",
        options_ar: ["لومه أمام الآخرين", "الاستماع له وتشجيعه دون ضغط", "إخباره أنه ضعيف", "تهديده"],
        options_en: ["Shame them publicly", "Listen and encourage without pressure", "Tell them they are weak", "Threaten them"],
        correct: 1,
        explanation_ar: "الدعم بلا حكم أكثر فعالية.",
        explanation_en: "Non-judgmental support is most effective.",
      },
      {
        id: "sup-2",
        question_ar: "هل اللوم المتكرر يساعد على الإقلاع؟",
        question_en: "Does repeated blame help quitting?",
        options_ar: ["نعم", "لا، قد يفاقم الوضع", "أحيانًا", "فقط للرجال"],
        options_en: ["Yes", "No, it can backfire", "Sometimes", "Only for men"],
        correct: 1,
        explanation_ar: "اللوم يزيد الإجهاد ويعطل التغيير.",
        explanation_en: "Blame raises stress and blocks change.",
      },
      {
        id: "sup-3",
        question_ar: "ماذا تفعل إذا انتكس قريبك؟",
        question_en: "What if your loved one relapses?",
        options_ar: ["تجاهله", "ادعمه على العودة للخطة", "اطرده", "صدمه عاطفيًا"],
        options_en: ["Ignore them", "Support them to return to the plan", "Cast them out", "Shock them emotionally"],
        correct: 1,
        explanation_ar: "الدعم اللطيف يحافظ على الثقة.",
        explanation_en: "Compassionate support preserves trust.",
      },
      {
        id: "sup-4",
        question_ar: "هل تشجيع الخطوات الصغيرة يفيد؟",
        question_en: "Is encouraging small steps helpful?",
        options_ar: ["لا", "نعم، يبني الزخم", "يبطئ التقدم", "يضيع وقتًا"],
        options_en: ["No", "Yes, it builds momentum", "Slows progress", "Wastes time"],
        correct: 1,
        explanation_ar: "الانتصارات الصغيرة تتراكم.",
        explanation_en: "Small wins compound over time.",
      },
      {
        id: "sup-5",
        question_ar: "هل يجب فرض موعد إقلاع على القريب؟",
        question_en: "Should you force a quit date on a loved one?",
        options_ar: ["نعم", "لا، الخيار يجب أن يكون له", "نعم بعد أسبوع", "نعم بعد شهر"],
        options_en: ["Yes", "No, the choice should be theirs", "Yes after a week", "Yes after a month"],
        correct: 1,
        explanation_ar: "الاستقلالية تعزز الالتزام.",
        explanation_en: "Autonomy strengthens commitment.",
      },
      {
        id: "sup-6",
        question_ar: "هل يمكنك اقتراح أدوات أقلع بلطف؟",
        question_en: "Can you gently suggest Aqla tools?",
        options_ar: ["لا", "نعم، مثل التقييم والمتطوعين والأدوات التفاعلية", "ممنوع", "فقط للمدخنين"],
        options_en: ["No", "Yes, like the assessment, volunteers, and interactive tools", "Forbidden", "Only for smokers"],
        correct: 1,
        explanation_ar: "اقتراح المصادر بلطف يساعد.",
        explanation_en: "Gentle suggestions of resources help.",
      },
      {
        id: "sup-7",
        question_ar: "ما الذي يجب تجنبه عند الدعم؟",
        question_en: "What should you avoid when supporting?",
        options_ar: ["التشجيع", "النقد القاسي والسخرية", "الاستماع", "اقتراح خطة"],
        options_en: ["Encouragement", "Harsh criticism and ridicule", "Listening", "Suggesting a plan"],
        correct: 1,
        explanation_ar: "السخرية تقوض الثقة.",
        explanation_en: "Ridicule undermines trust.",
      },
    ],
  },
  {
    slug: "myths",
    title_ar: "خرافات شائعة عن التدخين والنيكوتين",
    title_en: "Common Myths About Smoking and Nicotine",
    subtitle_ar: "افصل الحقيقة عن الخرافة.",
    subtitle_en: "Separate fact from fiction.",
    key_points_ar: [
      "التدخين لا يقلل التوتر فعليًا على المدى الطويل.",
      "السجائر \"الخفيفة\" ليست أكثر أمانًا.",
      "النيكوتين لا يحسّن التركيز فعليًا، بل يخفف انسحابه.",
    ],
    key_points_en: [
      "Smoking does not truly reduce long-term stress.",
      "\"Light\" cigarettes are not safer.",
      "Nicotine does not really boost focus — it relieves its own withdrawal.",
    ],
    did_you_know_ar: "كثير من \"الفوائد\" التي يشعر بها المدخن هي في الواقع تخفيف لأعراض الانسحاب من النيكوتين.",
    did_you_know_en: "Many \"benefits\" smokers feel are actually relief from nicotine withdrawal.",
    sources: [sources.who, sources.cdc, sources.smokefree],
    questions: [
      {
        id: "my-1",
        question_ar: "هل التدخين يقلل التوتر فعلًا على المدى الطويل؟",
        question_en: "Does smoking actually reduce stress long-term?",
        options_ar: ["نعم", "لا، الإحساس بالراحة يأتي من تخفيف الانسحاب", "فقط في الأزمات", "فقط بعد العمل"],
        options_en: ["Yes", "No, the calm comes from withdrawal relief", "Only in crises", "Only after work"],
        correct: 1,
        explanation_ar: "المدخنون عمومًا يبلغون عن مستويات توتر أعلى.",
        explanation_en: "Smokers generally report higher stress levels.",
      },
      {
        id: "my-2",
        question_ar: "هل السجائر \"الخفيفة\" أقل ضررًا؟",
        question_en: "Are \"light\" cigarettes less harmful?",
        options_ar: ["نعم", "لا، الضرر متشابه", "فقط للنساء", "فقط في الصباح"],
        options_en: ["Yes", "No, harm is similar", "Only for women", "Only in the morning"],
        correct: 1,
        explanation_ar: "هذه التسميات لا تعكس انخفاض الضرر.",
        explanation_en: "These labels do not reflect lower harm.",
      },
      {
        id: "my-3",
        question_ar: "هل النيكوتين يحسّن التركيز فعليًا؟",
        question_en: "Does nicotine truly improve focus?",
        options_ar: ["نعم", "لا، يخفف انسحابه فقط", "فقط في الامتحانات", "نعم للأطفال"],
        options_en: ["Yes", "No, it only relieves its own withdrawal", "Only during exams", "Yes for children"],
        correct: 1,
        explanation_ar: "ما يبدو تحسنًا هو عودة للوضع الأساسي.",
        explanation_en: "Apparent improvement is just a return to baseline.",
      },
      {
        id: "my-4",
        question_ar: "هل الإقلاع يسبب زيادة وزن كبيرة ومستمرة دائمًا؟",
        question_en: "Does quitting always cause large permanent weight gain?",
        options_ar: ["نعم دائمًا", "لا، يختلف بين الناس ويمكن إدارته", "كل المقلعين يكتسبون 20 كيلو", "الإقلاع يسبب نحافة فقط"],
        options_en: ["Yes always", "No, varies and can be managed", "All quitters gain 20kg", "Quitting only causes thinness"],
        correct: 1,
        explanation_ar: "زيادة الوزن قابلة للإدارة بالنشاط والتغذية.",
        explanation_en: "Weight changes are manageable with activity and nutrition.",
      },
      {
        id: "my-5",
        question_ar: "هل التدخين أقل ضررًا إذا تنفست بسطحية؟",
        question_en: "Is smoking less harmful if you inhale shallowly?",
        options_ar: ["نعم", "لا، الضرر لا يزال موجودًا", "نعم في الشتاء", "فقط للرياضيين"],
        options_en: ["Yes", "No, harm still occurs", "Yes in winter", "Only for athletes"],
        correct: 1,
        explanation_ar: "التعرض للمواد الضارة يبقى.",
        explanation_en: "Exposure to harmful compounds remains.",
      },
      {
        id: "my-6",
        question_ar: "هل النيكوتين \"طبيعي\" لذا فهو آمن؟",
        question_en: "Is nicotine \"natural\" and therefore safe?",
        options_ar: ["نعم", "لا، الطبيعي لا يعني الآمن", "آمن للأطفال", "آمن في الحمل"],
        options_en: ["Yes", "No, natural does not mean safe", "Safe for kids", "Safe in pregnancy"],
        correct: 1,
        explanation_ar: "كثير من المواد الطبيعية ليست آمنة.",
        explanation_en: "Many natural substances are not safe.",
      },
      {
        id: "my-7",
        question_ar: "هل الإقلاع \"فجأة\" خطر دائمًا؟",
        question_en: "Is quitting \"cold turkey\" always dangerous?",
        options_ar: ["نعم", "لا، آمن لمعظم الناس مع خطة ودعم", "آمن فقط في المستشفى", "غير ممكن"],
        options_en: ["Yes", "No, it is safe for most people with a plan and support", "Only safe in hospital", "Impossible"],
        correct: 1,
        explanation_ar: "كثير من الناس ينجحون بهذه الطريقة.",
        explanation_en: "Many people succeed this way.",
      },
    ],
  },
];

export function getModuleBySlug(slug: string) {
  return LEARN_MODULES.find((m) => m.slug === slug);
}

export function pickRandomQuestions(slug: string, n = 5): LearnQuestion[] {
  const m = getModuleBySlug(slug);
  if (!m) return [];
  const arr = [...m.questions];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, Math.min(n, arr.length));
}

export function computeBadge(score: number, completedModules: number, completedSupport: boolean): string | null {
  if (score === 100) return "Aqla Ambassador";
  if (score >= 80) return "Knowledge Champion";
  if (completedSupport) return "Quit Supporter";
  if (completedModules >= 3) return "Myth Buster";
  if (score >= 60) return "Awareness Starter";
  return null;
}

export const BADGE_LABELS: Record<string, { ar: string; en: string }> = {
  "Awareness Starter": { ar: "مبتدئ الوعي", en: "Awareness Starter" },
  "Myth Buster": { ar: "صائد الخرافات", en: "Myth Buster" },
  "Trigger Expert": { ar: "خبير المحفزات", en: "Trigger Expert" },
  "Quit Supporter": { ar: "داعم الإقلاع", en: "Quit Supporter" },
  "Knowledge Champion": { ar: "بطل المعرفة", en: "Knowledge Champion" },
  "Aqla Ambassador": { ar: "سفير أقلع", en: "Aqla Ambassador" },
};

export const WEEKLY_CHALLENGES = [
  { slug: "myths", ar: "أسبوع خرافات التدخين", en: "Smoking Myths Week" },
  { slug: "triggers", ar: "أسبوع المحفزات والرغبة", en: "Triggers and Cravings Week" },
  { slug: "support", ar: "أسبوع مساعدة الآخرين", en: "Supporting Others Week" },
  { slug: "vaping", ar: "أسبوع الفيب وأكياس النيكوتين", en: "Vaping and Nicotine Pouches Week" },
];

export function currentWeeklyChallenge() {
  // Rotate by ISO week so it cycles deterministically
  const now = new Date();
  const start = new Date(Date.UTC(now.getUTCFullYear(), 0, 1));
  const days = Math.floor((now.getTime() - start.getTime()) / 86400000);
  const week = Math.floor((days + start.getUTCDay()) / 7);
  return WEEKLY_CHALLENGES[week % WEEKLY_CHALLENGES.length];
}
