import { redirect } from 'next/navigation'
import VolunteerStatusControl from '@/components/VolunteerStatusControl'
import { getCurrentAqlaUser, hasAqlaRole } from '@/lib/current-user.server'
import { listVolunteerApplications } from '@/lib/volunteer.server'

export const dynamic='force-dynamic'
export default async function VolunteersAdminPage(){
 const user=await getCurrentAqlaUser();if(!user)redirect('/auth/login?returnTo=%2Faqla%2Fadmin%2Fvolunteers');if(!hasAqlaRole(user,'admin'))redirect('/aqla')
 const rows=await listVolunteerApplications(150)
 return <main className="eng-page" dir="ltr" lang="en"><div className="eng-shell"><header className="eng-top"><a className="eng-brand" href="/aqla/admin"><img src="/aqla-logo.png" alt="Aqla"/><span>Volunteer Operations</span></a><nav className="eng-nav"><a href="/aqla/admin/participants">Participant CRM</a><a href="/aqla/admin/research-exports">Research exports</a><a href="/aqla/admin">Command Centre</a></nav></header><section className="eng-card"><span className="eng-kicker">ADMIN / VOLUNTEERS</span><h1>Volunteer pipeline</h1><p className="eng-muted">Applications remain separate from participant clinical records. Status changes are operational only; approval should follow screening and required training.</p><div className="eng-stat-row"><div className="eng-stat"><span>Total loaded</span><strong>{rows.length}</strong></div><div className="eng-stat"><span>Submitted</span><strong>{rows.filter(r=>r.status==='submitted').length}</strong></div><div className="eng-stat"><span>Training</span><strong>{rows.filter(r=>r.status==='training').length}</strong></div><div className="eng-stat"><span>Active</span><strong>{rows.filter(r=>r.status==='active').length}</strong></div></div></section><section className="eng-card" style={{marginTop:16}}><div className="eng-table-wrap"><table className="eng-table"><thead><tr><th>Code</th><th>Name</th><th>City</th><th>Contact</th><th>Interests</th><th>Created</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.application_id}><td>{r.volunteer_code}</td><td>{r.full_name}</td><td>{r.city||'—'}</td><td>{r.email||r.mobile}</td><td>{r.interests.join(', ')}</td><td>{r.created_at?.slice(0,10)}</td><td><VolunteerStatusControl code={r.volunteer_code} initial={r.status}/></td></tr>)}</tbody></table></div>{!rows.length?<p className="eng-muted">No volunteer applications recorded yet.</p>:null}</section></div></main>
}
