'use client'

import { useMemo, useState } from 'react'

const TIMELINE_AR=[['20 دقيقة','يبدأ النبض وضغط الدم بالاتجاه نحو الطبيعي.'],['12 ساعة','ينخفض أول أكسيد الكربون في الدم نحو المستوى الطبيعي.'],['2–12 أسبوعًا','قد تتحسن الدورة الدموية ووظيفة الرئة.'],['1–9 أشهر','قد يقل السعال وضيق النفس تدريجيًا.'],['1 سنة','ينخفض خطر مرض القلب التاجي مقارنةً بالاستمرار بالتدخين.']]
const TIMELINE_EN=[['20 minutes','Heart rate and blood pressure begin moving toward normal.'],['12 hours','Blood carbon monoxide falls toward normal levels.'],['2–12 weeks','Circulation and lung function may improve.'],['1–9 months','Cough and breathlessness may gradually improve.'],['1 year','Coronary heart disease risk is lower than with continued smoking.']]
const TRIGGERS=[['coffee','القهوة','Coffee'],['car','السيارة','Car'],['after_meal','بعد الأكل','After meals'],['social','الأصدقاء والمجالس','Social settings'],['stress','التوتر','Stress'],['boredom','الملل','Boredom'],['study','الدراسة/العمل','Study/work'],['weekend','نهاية الأسبوع','Weekend']]

export default function ToolsPage(){
 const [lang,setLang]=useState<'ar'|'en'>('ar');const ar=lang==='ar'
 const [daily,setDaily]=useState(20);const [packSize,setPackSize]=useState(20);const [packPrice,setPackPrice]=useState(28)
 const [importance,setImportance]=useState(7);const [confidence,setConfidence]=useState(5);const [selected,setSelected]=useState<string[]>([])
 const dailyCost=useMemo(()=>packSize>0?(daily/packSize)*packPrice:0,[daily,packPrice,packSize]);const monthly=dailyCost*30;const yearly=dailyCost*365
 const readiness=importance>=7&&confidence>=7?(ar?'جاهزية جيدة للبدء بخطوة عملية':'Good readiness for a practical step'):importance>=7?(ar?'السبب قوي؛ ركّز الآن على رفع الثقة بخطوة صغيرة':'Motivation is strong; build confidence with one small step'):confidence>=7?(ar?'الثقة جيدة؛ وضّح السبب الشخصي للتغيير':'Confidence is good; clarify your personal reason for change'):(ar?'ابدأ بفهم النمط دون ضغط على نفسك':'Start by understanding your pattern without pressure')
 function toggle(k:string){setSelected(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k])}
 return <main className="eng-page" dir={ar?'rtl':'ltr'} lang={lang}><div className="eng-shell">
  <header className="eng-top"><a className="eng-brand" href="/aqla"><img src="/aqla-logo.png" alt="Aqla"/><span>أقلع | Aqla</span></a><nav className="eng-nav"><a href="/aqla/help-someone">{ar?'ساعد شخصًا':'Help someone'}</a><a href="/aqla/share">{ar?'المشاركة':'Share'}</a><button className="eng-btn" onClick={()=>setLang(ar?'en':'ar')}>{ar?'EN':'ع'}</button></nav></header>
  <section className="eng-card" style={{marginBottom:16}}><span className="eng-kicker">{ar?'أدوات أقلع':'Aqla tools'}</span><h1>{ar?'أدوات سريعة لفهم نمطك واتخاذ خطوة':'Quick tools to understand your pattern and take one step'}</h1><p className="eng-muted">{ar?'هذه الأدوات تعليمية وليست تشخيصًا طبيًا. نتائجها لا تُحفظ تلقائيًا في حسابك.':'These tools are educational, not diagnostic. Results are not automatically stored in your account.'}</p></section>
  <div className="eng-grid">
   <section className="eng-card"><h2>{ar?'حاسبة تكلفة التدخين':'Smoking cost calculator'}</h2><div className="eng-grid"><div className="eng-field"><label>{ar?'سجائر يوميًا':'Cigarettes/day'}</label><input type="number" min="0" max="200" value={daily} onChange={e=>setDaily(Math.max(0,Number(e.target.value)||0))}/></div><div className="eng-field"><label>{ar?'عدد السجائر في العلبة':'Pack size'}</label><input type="number" min="1" max="100" value={packSize} onChange={e=>setPackSize(Math.max(1,Number(e.target.value)||1))}/></div></div><div className="eng-field"><label>{ar?'سعر العلبة (ريال)':'Pack price (SAR)'}</label><input type="number" min="0" max="500" step="0.5" value={packPrice} onChange={e=>setPackPrice(Math.max(0,Number(e.target.value)||0))}/></div><div className="eng-result"><span>{ar?'تقريبًا في السنة':'Approx. per year'}</span><div className="eng-metric">{yearly.toLocaleString(ar?'ar-SA':'en-GB',{maximumFractionDigits:0})} SAR</div><small>{ar?`شهريًا ≈ ${monthly.toFixed(0)} ريال · هذا تقدير مالي وليس وعدًا بالتوفير.`:`Monthly ≈ SAR ${monthly.toFixed(0)} · This is a financial estimate, not a savings guarantee.`}</small></div></section>
   <section className="eng-card"><h2>{ar?'مقياس الاستعداد':'Readiness meter'}</h2><div className="eng-field"><label>{ar?`أهمية التغيير: ${importance}/10`:`Importance: ${importance}/10`}</label><input type="range" min="0" max="10" value={importance} onChange={e=>setImportance(Number(e.target.value))}/></div><div className="eng-field"><label>{ar?`الثقة بالقدرة على التغيير: ${confidence}/10`:`Confidence: ${confidence}/10`}</label><input type="range" min="0" max="10" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></div><div className="eng-result"><strong>{readiness}</strong><p className="eng-muted">{ar?'لا تستخدم هذه النتيجة كتشخيص أو حكم على نجاحك.':'Do not use this result as a diagnosis or prediction of success.'}</p></div></section>
   <section className="eng-card"><h2>{ar?'خريطة المحفزات':'Trigger map'}</h2><p className="eng-muted">{ar?'اختر المواقف التي غالبًا تدفعك لاستخدام النيكوتين.':'Choose situations that commonly cue nicotine use.'}</p><div className="eng-options">{TRIGGERS.map(t=><button className={`eng-chip ${selected.includes(t[0])?'active':''}`} key={t[0]} onClick={()=>toggle(t[0])}>{t[ar?1:2]}</button>)}</div>{selected.length?<div className="eng-note" style={{marginTop:14}}>{ar?'اختر واحدًا فقط هذا الأسبوع وغيّر الروتين المرتبط به بدل محاولة تغيير كل شيء دفعة واحدة.':'Choose just one this week and change the routine around it rather than changing everything at once.'}</div>:null}</section>
   <section className="eng-card"><h2>{ar?'تحدي تنفّس دقيقتين':'Two-minute breathing reset'}</h2><p className="eng-muted">{ar?'اجلس بأمان. خذ شهيقًا هادئًا من الأنف ثم زفيرًا أطول قليلًا. كرر ببطء لمدة دقيقتين.':'Sit somewhere safe. Breathe in gently through the nose, then breathe out a little longer. Repeat slowly for two minutes.'}</p><div className="eng-note">{ar?'ليس اختبارًا للرئة ولا علاجًا. أوقف التمرين إذا شعرت بدوار أو عدم ارتياح.':'This is not a lung test or treatment. Stop if you feel dizzy or uncomfortable.'}</div><div className="eng-actions"><a className="eng-btn primary" href="/aqla/sos">{ar?'افتح مساعدة الرغبة':'Open craving support'}</a></div></section>
  </div>
  <section className="eng-card" style={{marginTop:16}}><h2>{ar?'ماذا قد يحدث بعد التوقف عن التدخين؟':'What may change after stopping smoking?'}</h2><ul className="eng-list">{(ar?TIMELINE_AR:TIMELINE_EN).map(([time,text])=><li key={time}><strong>{time}</strong><div className="eng-muted">{text}</div></li>)}</ul><p className="eng-muted">{ar?'المسار يختلف بين الأشخاص، وقد تحتاج أعراض أو أمراض موجودة إلى تقييم طبي مستقل.':'Recovery varies between people, and existing symptoms or conditions may need separate medical assessment.'}</p></section>
  <footer className="eng-footer">Aqla — أقلع</footer>
 </div></main>
}
