/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SupportInviteRouteImport } from './routes/support-invite'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as QuitPathwayRouteImport } from './routes/quit-pathway'
import { Route as PosterStudioRouteImport } from './routes/poster-studio'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HelpPathwayRouteImport } from './routes/help-pathway'
import { Route as CityChallengeRouteImport } from './routes/city-challenge'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ChallengePathwayRouteImport } from './routes/challenge-pathway'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as AdminDataDictionaryRouteImport } from './routes/admin.data-dictionary'
import { Route as ShareTypeIdRouteImport } from './routes/share.$type.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportInviteRoute = SupportInviteRouteImport.update({
  id: '/support-invite',
  path: '/support-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const QuitPathwayRoute = QuitPathwayRouteImport.update({
  id: '/quit-pathway',
  path: '/quit-pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterStudioRoute = PosterStudioRouteImport.update({
  id: '/poster-studio',
  path: '/poster-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPathwayRoute = HelpPathwayRouteImport.update({
  id: '/help-pathway',
  path: '/help-pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const CityChallengeRoute = CityChallengeRouteImport.update({
  id: '/city-challenge',
  path: '/city-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengePathwayRoute = ChallengePathwayRouteImport.update({
  id: '/challenge-pathway',
  path: '/challenge-pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataDictionaryRoute = AdminDataDictionaryRouteImport.update({
  id: '/data-dictionary',
  path: '/data-dictionary',
  getParentRoute: () => AdminRoute,
} as any)
const ShareTypeIdRoute = ShareTypeIdRouteImport.update({
  id: '/share/$type/$id',
  path: '/share/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/challenge-pathway': typeof ChallengePathwayRoute
  '/challenges': typeof ChallengesRoute
  '/city-challenge': typeof CityChallengeRoute
  '/help-pathway': typeof HelpPathwayRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/movement': typeof MovementRoute
  '/poster-studio': typeof PosterStudioRoute
  '/quit-pathway': typeof QuitPathwayRoute
  '/shop': typeof ShopRoute
  '/support-invite': typeof SupportInviteRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/data-dictionary': typeof AdminDataDictionaryRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/challenge-pathway': typeof ChallengePathwayRoute
  '/challenges': typeof ChallengesRoute
  '/city-challenge': typeof CityChallengeRoute
  '/help-pathway': typeof HelpPathwayRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/movement': typeof MovementRoute
  '/poster-studio': typeof PosterStudioRoute
  '/quit-pathway': typeof QuitPathwayRoute
  '/shop': typeof ShopRoute
  '/support-invite': typeof SupportInviteRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/data-dictionary': typeof AdminDataDictionaryRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/challenge-pathway': typeof ChallengePathwayRoute
  '/challenges': typeof ChallengesRoute
  '/city-challenge': typeof CityChallengeRoute
  '/help-pathway': typeof HelpPathwayRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/movement': typeof MovementRoute
  '/poster-studio': typeof PosterStudioRoute
  '/quit-pathway': typeof QuitPathwayRoute
  '/shop': typeof ShopRoute
  '/support-invite': typeof SupportInviteRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/data-dictionary': typeof AdminDataDictionaryRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/share/$type/$id': typeof ShareTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/challenge-pathway'
    | '/challenges'
    | '/city-challenge'
    | '/help-pathway'
    | '/learn'
    | '/login'
    | '/movement'
    | '/poster-studio'
    | '/quit-pathway'
    | '/shop'
    | '/support-invite'
    | '/tools'
    | '/training'
    | '/volunteer'
    | '/admin/data-dictionary'
    | '/certificate/$code'
    | '/share/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/challenge-pathway'
    | '/challenges'
    | '/city-challenge'
    | '/help-pathway'
    | '/learn'
    | '/login'
    | '/movement'
    | '/poster-studio'
    | '/quit-pathway'
    | '/shop'
    | '/support-invite'
    | '/tools'
    | '/training'
    | '/volunteer'
    | '/admin/data-dictionary'
    | '/certificate/$code'
    | '/share/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/challenge-pathway'
    | '/challenges'
    | '/city-challenge'
    | '/help-pathway'
    | '/learn'
    | '/login'
    | '/movement'
    | '/poster-studio'
    | '/quit-pathway'
    | '/shop'
    | '/support-invite'
    | '/tools'
    | '/training'
    | '/volunteer'
    | '/admin/data-dictionary'
    | '/certificate/$code'
    | '/share/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  ChallengePathwayRoute: typeof ChallengePathwayRoute
  ChallengesRoute: typeof ChallengesRoute
  CityChallengeRoute: typeof CityChallengeRoute
  HelpPathwayRoute: typeof HelpPathwayRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MovementRoute: typeof MovementRoute
  PosterStudioRoute: typeof PosterStudioRoute
  QuitPathwayRoute: typeof QuitPathwayRoute
  ShopRoute: typeof ShopRoute
  SupportInviteRoute: typeof SupportInviteRoute
  ToolsRoute: typeof ToolsRoute
  TrainingRoute: typeof TrainingRoute
  VolunteerRoute: typeof VolunteerRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  ShareTypeIdRoute: typeof ShareTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-invite': {
      id: '/support-invite'
      path: '/support-invite'
      fullPath: '/support-invite'
      preLoaderRoute: typeof SupportInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quit-pathway': {
      id: '/quit-pathway'
      path: '/quit-pathway'
      fullPath: '/quit-pathway'
      preLoaderRoute: typeof QuitPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-studio': {
      id: '/poster-studio'
      path: '/poster-studio'
      fullPath: '/poster-studio'
      preLoaderRoute: typeof PosterStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-pathway': {
      id: '/help-pathway'
      path: '/help-pathway'
      fullPath: '/help-pathway'
      preLoaderRoute: typeof HelpPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-challenge': {
      id: '/city-challenge'
      path: '/city-challenge'
      fullPath: '/city-challenge'
      preLoaderRoute: typeof CityChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-pathway': {
      id: '/challenge-pathway'
      path: '/challenge-pathway'
      fullPath: '/challenge-pathway'
      preLoaderRoute: typeof ChallengePathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-dictionary': {
      id: '/admin/data-dictionary'
      path: '/data-dictionary'
      fullPath: '/admin/data-dictionary'
      preLoaderRoute: typeof AdminDataDictionaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/share/$type/$id': {
      id: '/share/$type/$id'
      path: '/share/$type/$id'
      fullPath: '/share/$type/$id'
      preLoaderRoute: typeof ShareTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDataDictionaryRoute: typeof AdminDataDictionaryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDataDictionaryRoute: AdminDataDictionaryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  ChallengePathwayRoute: ChallengePathwayRoute,
  ChallengesRoute: ChallengesRoute,
  CityChallengeRoute: CityChallengeRoute,
  HelpPathwayRoute: HelpPathwayRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MovementRoute: MovementRoute,
  PosterStudioRoute: PosterStudioRoute,
  QuitPathwayRoute: QuitPathwayRoute,
  ShopRoute: ShopRoute,
  SupportInviteRoute: SupportInviteRoute,
  ToolsRoute: ToolsRoute,
  TrainingRoute: TrainingRoute,
  VolunteerRoute: VolunteerRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  ShareTypeIdRoute: ShareTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
