'use client'

import { useEffect, useMemo, useState } from 'react'
import { CHALLENGES, type ChallengeId } from '@/lib/challenges.types'

type Progress={challenge_id:string;state:string;joined_at?:string;completed_at?:string;points_awarded:number}
type Stats={minimum_city_cell:number;totals:{challenge_joins:number;challenge_completions:number;points_awarded:number;cities_visible:number};challenges:{challenge_id:string;joined_count:number;completed_count:number;points_awarded:number}[];cities:{city:string;engagement_count:number;challenge_joins:number}[];other_small_cell_engagement:number}

function cityLabel(value:string){return value.split(' ').map(p=>p?`${p[0].toUpperCase()}${p.slice(1)}`:p).join(' ')}
export default function ChallengeHub(){
 const [lang,setLang]=useState<'ar'|'en'>('ar');const ar=lang==='ar';const [stats,setStats]=useState<Stats|null>(null);const [mine,setMine]=useState<Progress[]>([]);const [signedIn,setSignedIn]=useState<boolean|null>(null);const [city,setCity]=useState('');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('')
 async function load(){try{const s=await fetch('/api/challenges',{cache:'no-store'});if(s.ok)setStats(await s.json())}catch{}try{const m=await fetch('/api/challenges/mine',{cache:'no-store'});if(m.ok){const data=await m.json();setMine(data.challenges||[]);setSignedIn(true)}else if(m.status===401)setSignedIn(false)}catch{setSignedIn(false)}}
 useEffect(()=>{void load()},[])
 const progress=useMemo(()=>new Map(mine.map(p=>[p.challenge_id,p])),[mine]);const earned=mine.reduce((sum,p)=>sum+(p.state==='completed'?p.points_awarded:0),0)
 async function act(id:ChallengeId,action:'join'|'complete'){
  setBusy(`${id}:${action}`);setNotice('');try{const res=await fetch('/api/challenges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_id:id,action,city:city.trim()||undefined})});const data=await res.json();if(res.status===401){window.location.href=`/auth/login?returnTo=${encodeURIComponent('/aqla/challenges')}`;return}if(!res.ok){if(data.error==='day_28_not_due')setNotice(ar?'تحدي 28 يومًا لا يمكن إكماله قبل مرور 28 يومًا من الانضمام.':'The 28-day challenge cannot be completed until 28 days after joining.');else if(data.error==='academy_completion_required')setNotice(ar?'تحدي المعرفة يُحتسب تلقائيًا من نتيجة الأكاديمية، وليس بزر يدوي.':'The Knowledge Challenge is awarded from Academy evidence, not a manual button.');else setNotice(ar?'تعذر تحديث التحدي الآن.':'Could not update the challenge.');return}await load();setNotice(action==='join'?(ar?'تم الانضمام للتحدي ✓':'Challenge joined ✓'):(ar?`اكتمل التحدي وأضيفت ${data.points||0} نقطة ✓`:`Challenge completed and ${data.points||0} points added ✓`))}finally{setBusy('')}}
 function due28(p?:Progress){if(!p?.joined_at)return false;return Date.now()-Date.parse(p.joined_at)>=28*86400000}
 return <main className="eng-page" dir={ar?'rtl':'ltr'} lang={lang}><div className="eng-shell">
  <header className="eng-top"><a className="eng-brand" href="/aqla"><img src="/aqla-logo.png" alt="Aqla"/><span>أقلع | Aqla</span></a><nav className="eng-nav"><a href="/aqla/tools">{ar?'الأدوات':'Tools'}</a><a href="/aqla/poster-studio">{ar?'الملصقات':'Posters'}</a><a href="/aqla/volunteer">{ar?'التطوع':'Volunteer'}</a><button className="eng-btn" onClick={()=>setLang(ar?'en':'ar')}>{ar?'EN':'ع'}</button></nav></header>
  <section className="eng-card" style={{marginBottom:16}}><span className="eng-kicker">{ar?'مركز التحديات والمجتمع':'Challenge & Community Hub'}</span><h1>{ar?'تحديات تكافئ المشاركة والوعي — لا الحالة الصحية':'Challenges that reward participation and awareness — not health status'}</h1><p className="eng-muted">{ar?'لا توجد نقاط لأنك أقلعت أسرع من غيرك، ولا نخسر نقاطًا عند الزلة. النقاط هنا لخطوات التعلم، الدعم، الوعي والمشاركة المجتمعية.':'There are no points for quitting faster than someone else and no penalty for a slip. Points recognise learning, support, awareness and community participation.'}</p><div className="eng-note">{ar?'لوحات المدن تعرض أرقامًا مجمعة فقط. المدينة لا تظهر منفردة حتى تصل إلى حد أدنى لحماية الخصوصية.':'City figures are aggregate only. A city is not shown individually until the minimum privacy threshold is reached.'}</div></section>
  <section className="eng-stat-row" style={{marginBottom:16}}><div className="eng-stat"><span>{ar?'الانضمامات':'Challenge joins'}</span><strong>{stats?.totals.challenge_joins??'—'}</strong></div><div className="eng-stat"><span>{ar?'تحديات مكتملة':'Completed'}</span><strong>{stats?.totals.challenge_completions??'—'}</strong></div><div className="eng-stat"><span>{ar?'نقاط مجتمعية':'Community points'}</span><strong>{stats?.totals.points_awarded??'—'}</strong></div><div className="eng-stat"><span>{ar?'نقاطي':'My points'}</span><strong>{signedIn?earned:'—'}</strong></div></section>
  <section className="eng-card" style={{marginBottom:16}}><div className="eng-field" style={{maxWidth:420}}><label>{ar?'مدينتك — اختيارية عند الانضمام':'Your city — optional when joining'}</label><input value={city} maxLength={80} onChange={e=>setCity(e.target.value)} placeholder={ar?'مثال: جدة':'e.g. Jeddah'}/><small className="eng-muted">{ar?`لن تظهر مدينة بشكل منفرد قبل ${stats?.minimum_city_cell??10} مشاركات على الأقل.`:`A city will not be shown individually before at least ${stats?.minimum_city_cell??10} engagements.`}</small></div>{notice?<div className="eng-note">{notice}</div>:null}</section>
  <div className="eng-grid three">{CHALLENGES.map(c=>{const p=progress.get(c.id);const aggregate=stats?.challenges.find(x=>x.challenge_id===c.id);const knowledge=c.id==='knowledge';const day28=c.id==='day_28';const canComplete=p?.state==='joined'&&!knowledge&&(!day28||due28(p));return <article className="eng-card" key={c.id}><span className="eng-kicker">+{c.points} {ar?'نقطة':'points'}</span><h2>{ar?c.title_ar:c.title_en}</h2><p className="eng-muted">{ar?c.body_ar:c.body_en}</p><div className="eng-progress"><span style={{width:p?.state==='completed'?'100%':p?'50%':'0%'}}/></div><p className="eng-muted"><small>{aggregate?(ar?`${aggregate.joined_count} انضموا · ${aggregate.completed_count} أكملوا`:`${aggregate.joined_count} joined · ${aggregate.completed_count} completed`):(ar?'لا توجد أرقام بعد':'No aggregate data yet')}</small></p><div className="eng-actions">{!p?<button className="eng-btn primary" disabled={busy!==''} onClick={()=>void act(c.id,'join')}>{ar?'انضم':'Join'}</button>:<span className={`eng-kicker ${p.state==='completed'?'eng-success':''}`}>{p.state==='completed'?(ar?'مكتمل ✓':'Completed ✓'):(ar?'منضم':'Joined')}</span>}<a className="eng-btn" href={c.href}>{ar?'افتح النشاط':'Open activity'}</a>{canComplete?<button className="eng-btn" disabled={busy!==''} onClick={()=>void act(c.id,'complete')}>{ar?'أنجزت الخطوة':'I completed the activity'}</button>:null}</div>{knowledge&&p?.state==='joined'?<small className="eng-muted">{ar?'الإكمال سيأتي تلقائيًا من سجل الأكاديمية بعد اجتياز المتطلب.':'Completion will come automatically from Academy evidence after the requirement is passed.'}</small>:null}{day28&&p?.state==='joined'&&!due28(p)?<small className="eng-muted">{ar?'سيظهر زر الإكمال بعد مرور 28 يومًا من تاريخ الانضمام.':'The completion control becomes available 28 days after joining.'}</small>:null}</article>})}</div>
  <section className="eng-card" style={{marginTop:16}}><h2>{ar?'المدن الأكثر تفاعلًا':'Most engaged cities'}</h2><p className="eng-muted">{ar?`تعرض فقط المدن التي وصلت إلى ${stats?.minimum_city_cell??10} مشاركات أو أكثر. التفاعلات الأقل تُجمع ولا تُنسب إلى مدينة علنًا.`:`Only cities reaching ${stats?.minimum_city_cell??10} engagements are shown. Smaller cells are pooled and not publicly attributed to a city.`}</p>{stats?.cities.length?<div className="eng-grid three">{stats.cities.slice(0,9).map((c,i)=><div className="eng-stat" key={c.city}><span>#{i+1} {cityLabel(c.city)}</span><strong>{c.engagement_count}</strong><small>{ar?'تفاعل مجتمعي':'community engagements'}</small></div>)}</div>:<div className="eng-note">{ar?'لا توجد مدينة وصلت إلى حد العرض الآمن بعد.':'No city has reached the safe display threshold yet.'}</div>}{stats&&stats.other_small_cell_engagement>0?<p className="eng-muted"><small>{ar?`${stats.other_small_cell_engagement} تفاعل إضافي محفوظ ضمن خلايا صغيرة غير معروضة.`:`${stats.other_small_cell_engagement} additional engagements are held in non-displayed small cells.`}</small></p>:null}</section>
  <section className="eng-card" style={{marginTop:16}}><h2>{ar?'مسارات المجتمع':'Community pathways'}</h2><div className="eng-grid three"><a className="eng-btn" href="/aqla/help-someone">{ar?'ساعد شخصًا باحترام':'Help someone respectfully'}</a><a className="eng-btn" href="/aqla/poster-studio">{ar?'صمم ملصقًا توعويًا':'Create an awareness poster'}</a><a className="eng-btn" href="/aqla/volunteer">{ar?'انضم للمتطوعين':'Join volunteers'}</a><a className="eng-btn" href="/aqla/academy">{ar?'تعلم في الأكاديمية':'Learn in Academy'}</a><a className="eng-btn" href="/aqla/share">{ar?'مشاركة آمنة':'Privacy-safe sharing'}</a><a className="eng-btn" href="/aqla/tools">{ar?'أدوات أقلع':'Aqla tools'}</a></div></section>
  <footer className="eng-footer">Aqla — أقلع · {ar?'مشاركة مجتمعية بدون عرض بيانات صحية فردية':'Community participation without individual health disclosure'}</footer>
 </div></main>
}
